- src/components/beagle-page-view/beagle-page-view.component.html
- src/components/beagle-page-view/beagle-page-view.component.ts
- src/components/schemas/page-view.ts
As pageview will be used to simulate a tabview behavior, the arrows can't be always shown. Therefore, we added an optional prop `showArrow` that will be used to hide the arrows to support the cases where the pageview is together with the tabBar
Add optional prop in interface and component
Playground examples. Both, tabbar and pageview should be render correctly.
Add show arrow prop
> Add show arrow

- .github/workflows/publish.yml
- .github/workflows/validate.yml
Added clean cache before install command.
Added clean cache before install command.
On PR to master must run cache clean.
Added clean cache before install command.
> added clear cache before install on actions

- package.json
> releases v1.1.0

- .github/workflows/validate.yml
Added validation to owner of repository on PR. If ZupIT comment on PR coverage tests, if not don't comment, only run tests.
Added configuration to validation action.
When a PR is open, if owner is ZupIT must comment coveragem on PR, if not just run tests and don't comment coverage.
Added validation to owner of repository on PR.
> added validation owner to validate action

- package.json
Added support to es5
Using new version of beagle-web-core, which adds support to es5
Playground, beagle-forms
> updates package.json to reference core 1.1.1 so es5 is supported

- src/components/beagle-button/beagle-button.component.ts
- src/components/beagle-container/beagle-container.component.ts
- src/components/beagle-future-list-view/beagle-list-view.component.ts
- src/components/beagle-image/beagle-image.component.ts
- src/components/beagle-tab-bar/beagle-tab-bar.component.ts
- src/components/beagle-touchable/beagle-touchable.component.ts
- src/runtime/AbstractBeagleRemoteView.ts
- src/runtime/beagle-context/directive.ts
- src/runtime/utils/beagle-map-keys-config.ts
- src/types.ts
Adapts beagle-angular to work with the new structure of beagle-web-core.
Updated imports and some services usage.
I ran this version of the lib for both Beagle Forms and Beagle Playground (every demo example + global context).
Adapts beagle-angular to work with the new structure of beagle-web-core.
> Updates beagle-angular according to the new core structure

- package.json
Updates package.json versions so the developer can handle the strategy param at beagle config.
Increase the versions of beagle web core to use the fixed version and update beagle angular owns version.
Playground and  angular/show-default-components poc 
Update version to 1.1.2
> Change version for strategy correction

- package.json
> releases v1.2.0-beta-0

- package.json
> Release/1.2.0 beta.1

- src/components/beagle-tab-view/beagle-tab-view.lifecycles.ts
Better typing for the lifecycle of the component TabView.
This was not necessary for the code to work. I did it because it's the only example we have of applying a lifecycle, and for this reason, I think it should be 100% correct.
Just changed the types.
> fixing lifecycle type

- package.json
> releases v1.2.0

- package.json
> pre-release 1.3.0 rc1

- package.json
> releases 1.3.0

- README.md
I added badges, fixed a typo and also added the link for License which wasn't working in README.md.
Contributes to issue #202
> Updated badges and links

- README.md
> Updated badges and links (#203)

- package.json
Releases 1.5.0-rc.1 (pre-release)
Check it out in Playground Beta: http://playground-beta.usebeagle.io/
> Releases 1.5.0-rc.1 (pre-release)

- package.json
> Releases 1.7.0

- src/components/beagle-list-view/beagle-list-view.component.ts
closes #246 
Fixes linked issue
Changed the way the datasource variable was being initialized
Create a simple listview
> Changes datasource initialization

- src/components/beagle-image/beagle-image.component.less
I added border radius in the beagle image component.
I added border-radius: inherit; in figure.
Open playground with this payload https://run.mocky.io/v3/f7aaa09b-21a1-4d91-9d3d-0c6d44cddcfd
Closes: #255
> add border-radius

- src/components/beagle-modal/beagle-modal.component.ts
- src/components/beagle-text-area/beagle-text-area.component.ts
- src/components/schemas/modal.ts
- src/components/schemas/text-area.ts
Deprecated the custom components modal and text-area
> Deprecated custom modal and text-area

- src/constants.ts
Added pullToRefresh component
Added pullToRefresh component in default components
"_beagleComponent_": "beagle:pullToRefresh",
Closes: https://github.com/ZupIT/beagle/issues/1626
> Added pullToRefresh component

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/publish.yml
- .github/workflows/validate.yml
- CONTRIBUTING.md
- README.md
Renamed branch master to main on github actions
Link to the issue https://github.com/ZupIT/beagle/issues/1577
> feat: Rename master to main

- package.json
- src/cli/operations/init/angular.ts
**What I did?**
updated perrDependencies to `>= 7 <= 12`
> peerDependencies updated

- .gitattributes
- src/components/dynamic-lists/dynamic-list.component.ts
Improved the logic of `componentManager` for lists and add EOL config for git
> Fix: List componentManager improvements and git eol

- CONTRIBUTING.md
- README.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
Updated README section, added the new pattern. 
**- Description for the changelog** Updated README.
> Updated readme

- README.md
Added Best Practices Badge to README description
> Adds best practices badge to README file

- SECURITY.md
> Adds security policy

- .github/dependabot.yml
> Updates dependabot schedule

- .github/workflows/auto-comment.yml
- Added auto comment action for newly opened Pull Requests and Issues
> Adds auto comment action

- tsconfig.cli.json
- tsconfig.json
> skip lib check when compiling

- horusec-config.json
- src/__tests__/components/__snapshots__/beagle-button.spec.ts.snap
- src/components/beagle-button/beagle-button.component.html
- src/components/beagle-button/beagle-button.component.ts
Fixed button text now when an object is passed it is displayed in string
Story ID: 217157
**Description for the changelog**
Related story: https://app.shortcut.com/orange-stack/story/217157/buttons-don-t-work-with-wild-types-of-texts-on-beagle-react?stories_sort_by=priority&stories_group_by=WORKFLOW_STATE
> Fix button text

- .github/workflows/header.license-checker.yml
Updated action for license header checking
> Updates header license

- src/runtime/BeagleProvider.service.ts
I added platform as a parameter when creating a ViewClient, to use it in the header when making the request. To be aligned to the backend when using setPlatform
> add platform to additionalData

- .github/workflows/horusec.yml
Added Horusec web manager token
> Adds horusec web token

- package.json
- src/cli/operations/init/questions.ts
- src/index.ts
Signed-off-by: Arthur Bleil <arthur.bleil@zup.com.br>
- Fixed the link of the starting sample
- Updated the react version
- Create a new angular project following the tutorial.
- Fixed the link of the starting sample
- Updated the react version
> fix sample url

- README.md
- package.json
- src/codegen/compiled/beagle.module/imports.ts
Removes references to LoadParams and Injectable import from main beagle module
> fix: injectable
